name: Check Broken Links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install Lychee via cargo
        run: cargo install lychee

      - name: Run Lychee link checker with verbose output
        run: |
          lychee --verbose --no-progress --include-external --exclude-mail --output markdown ./
