name: Check Broken Links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Lychee link checker
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          args: --verbose --no-progress --output markdown --include-external
