name: Check Broken Links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Lychee
        run: |
          curl -sSfL https://github.com/lycheeverse/lychee/releases/latest/download/lychee-linux-x86_64.tar.gz | tar -xz
          chmod +x lychee
          sudo mv lychee /usr/local/bin/

      - name: Run Lychee link checker with verbose output
        run: |
          lychee --verbose --no-progress --exit-on-error --output markdown --include-external --exclude-mail ./
